manager: 127.0.0.1:6620
tcp: 0.0.0.0:1248
kcp: 0.0.0.0:1248
ws: 0.0.0.0:1249
scp:
  handshake_timeout: 30
  reuse_time: 30
  reuse_buffer: 65536
tcp_option:
  read_timeout: 0
  keepalive: true
  keepalive_interval: 60
kcp_option:
  read_timeout: 60
  fec_data_shards: 0
  fec_parity_shards: 0
  read_buffer: 4194304
  write_buffer: 4194304
  opt_mtu: 1400
  opt_nodelay: 1
  opt_interval: 10 # ms
  opt_resend: 2
  opt_nc: 1
  opt_sndwnd: 2048
  opt_rcvwnd: 2048
  opt_stream: true
ws_option:
  cert_file:
  key_file:
  backlog: 128
  handshake_timeout: 0
  frame_size: 4096
  read_buffer: 4096
  write_buffer: 4096
  read_timeout: 0
upstream_option:
  net: tcp
#  resolv:
#    port: 443
#    suffix: .com
#    prefix: mail.
#    pattern : google
hosts:
  - name: test1
    addr: 127.0.0.1:11248
    weight: 100
  - name: test2
    addr: 127.0.0.1:11249
    weight: 100
